- backend/corpora/rechtspraak/description/rechtspraak.md
- backend/corpora/rechtspraak/rechtspraak.py
Basic description file for the rechtspraak corpus.
> add description for rechtspraak

- frontend/src/app/filter/boolean-filter.component.html
- frontend/src/app/filter/boolean-filter.component.spec.ts
> fix boolean filter

- backend/addcorpus/corpus.py
This branch is improperly named hotfix - since the highlight PR was not yet released, merging into develop will do for now, and will ensure that we can deploy even if we don't define the `NEW_HIGHLIGHT_CORPORA` variable in the settings.
> fix deployment for NEW_HIGHLIGHT_CORPORA

- frontend/src/app/visualization/visualization.component.ts
fixes a bug introduced in #1226
> fix issue when field.visualizations == []

- frontend/src/app/word-models/word-models.component.ts
> fix getting word model query from route

- frontend/src/app/document-view/document-view.component.html
- frontend/src/app/document-view/document-view.component.spec.ts
- frontend/src/app/services/corpus.service.spec.ts
Fixes issue where the image tab in the document view had no text content.
close #1278
> fix image tab missing text

- frontend/.eslintrc.json
- frontend/src/app/app.component.html
- frontend/src/app/app.module.ts
- frontend/src/app/footer/footer.component.ts
- frontend/src/app/menu/menu.component.html
- frontend/src/app/menu/menu.component.scss
- frontend/src/app/menu/menu.component.ts
- frontend/src/app/services/auth.service.ts
- frontend/src/app/shared/tabs/tabs.component.html
Some accessibility improvements to the navbar:
- The menu toggle on mobile is now keyboard accessible
- The user dropdown has improved keyboard accessibility (see #794)
- Adds "skip to content link" at the start
- With the exception of logging out, menu items have an `href` link, rather than triggering a script event that sets the route. This makes links more predictable for users.
- Use `<header>` and `<footer>` in the app component so the header/footer get appropriate roles.
I've also cleaned up the logic of the navbar CSS and typescript. There were some arcane bits of logic without an adequate explanation of what they were for, so I *hope* it all works as before.
One final improvement is that the header is now visible when logged out, which also means new users can view the "about" …
> Navbar improvements

- backend/corpora/peaceportal/iis.py
- backend/corpora/peaceportal/peaceportal.py
- backend/corpora/peaceportal/tests/test_peace.py
Tests are now passing, let's hope this fixes the problem.
> close #1328: use glob over os.walk

- frontend/src/app/word-models/similarity-chart/time-interval-slider/time-interval-slider.component.html
> Use currentIndex for word model time slider

- frontend/src/app/image-view/image-view.component.html
- frontend/src/app/manual/manual-navigation.component.ts
- frontend/src/app/search/search.component.html
> small fixes

- frontend/src/app/download/download-options/download-options.component.html
- frontend/src/app/download/download-options/download-options.component.ts
- frontend/src/app/download/download.component.html
> Base DownloadOptionsComponent loading spinner on parent DownloadComponent

- frontend/src/app/visualization/barchart/barchart-options.component.html
- frontend/src/app/visualization/barchart/barchart-options.component.scss
> fix mobile layout of barchart options menu 

- backend/addcorpus/constants.py
> Forbid 'scan' and 'tab-scan' field names

- backend/corpora/jewishmigration/jewishmigration.py
Workaround for the VPN-capability-poor.
> Allow loading local JMIG sources

- backend/visualization/views.py
> don't require authentication for field coverage

- frontend/src/app/about/about.component.ts
- frontend/src/app/corpus-info/corpus-info.component.ts
- frontend/src/app/document-page/document-page.component.ts
- frontend/src/app/history/download-history/download-history.component.ts
- frontend/src/app/history/search-history/search-history.component.ts
- frontend/src/app/home/home.component.ts
- frontend/src/app/login/login.component.html
- frontend/src/app/login/login.component.ts
- frontend/src/app/login/registration/registration.component.ts
- frontend/src/app/login/reset-password/request-reset.component.ts
- frontend/src/app/login/reset-password/reset-password.component.html
- frontend/src/app/login/reset-password/reset-password.component.ts
- frontend/src/app/login/verify-email/verify-email.component.ts
- frontend/src/app/manual/manual.component.ts
- frontend/src/app/menu/menu.component.ts
- frontend/src/app/privacy/privacy.component.html
- frontend/src/app/privacy/privacy.component.ts
- frontend/src/app/search/search.component.ts
- frontend/src/app/settings/settings.component.ts
- frontend/src/app/tag/tag-overview/tag-overview.component.ts
- frontend/src/app/utils/app.ts
- frontend/src/app/word-models/word-models.component.ts
> add page titles

- frontend/src/app/visualization/ngram/ngram.component.html
Resolves #1594
Confirmed working on acceptation server.
> Use correct options in ngram compensation dropdown

- backend/media/views.py
Can all issues be this simple forever please?
> Remove IsAuthenticated permission from media views

- CITATION.cff
- README.md
- backend/addcorpus/schemas/corpus.schema.json
- documentation/Authentication-and-authorization.md
- documentation/Local-Debian-I-Analyzer-setup.md
- documentation/Making-a-release.md
- frontend/src/assets/about/en-GB/ianalyzer.md
- frontend/src/environments/environment.git.ts
- frontend/src/environments/environment.ts
Updates the repository URL to reflect organisation transfer.
> Update repository URL

- backend/corpora/times/times.py
> fix date sorting in times corpus

- frontend/src/app/filter/tag-filter/tag-filter.component.html
> show tag filter value when loading page

- backend/corpora/parliament/description/uk.md
This was requested by Jo Guldi.
> Add acknowledgement and link to dataverse for UK data

- backend/ianalyzer/common_settings.py
- frontend/src/app/services/api.service.ts
- frontend/src/app/services/auth.service.ts
- frontend/src/app/settings/change-password/change-password.component.html
- frontend/src/app/settings/change-password/change-password.component.scss
- frontend/src/app/settings/change-password/change-password.component.spec.ts
- frontend/src/app/settings/change-password/change-password.component.ts
- frontend/src/app/settings/search-history-settings/search-history-settings.component.html
- frontend/src/app/settings/settings.component.html
- frontend/src/app/settings/settings.component.ts
- frontend/src/app/settings/settings.module.ts
- frontend/src/mock-data/auth.ts
Adds a "change password" form to the user settings. close #1314
> Change password

- backend/users/serializers.py
- frontend/src/app/models/user.ts
- frontend/src/app/settings/change-username/change-username.component.html
- frontend/src/app/settings/change-username/change-username.component.spec.ts
- frontend/src/app/settings/change-username/change-username.component.ts
- frontend/src/app/settings/settings.component.html
- frontend/src/app/settings/settings.module.ts
- frontend/src/mock-data/auth.ts
- frontend/src/styles.scss
Small feature: adds the option to change your username in the settings menu.
> change username

- frontend/src/app/visualization/barchart/timeline.component.ts
Close #1849 - turned out to be a super easy fix :+1:
> fix x domain on timeline graph

- frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.html
- frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.ts
- frontend/src/app/shared/shared.module.ts
> fix date picker  onChange

- frontend/yarn.lock
Upgrades frontend packages. (No changes to the specified version ranges in `package.json`.)
> upgrade packages (frontend)
