CentreForDigitalHumanities/I-analyzer

- frontend/src/app/filter/range-filter.component.html
- frontend/src/app/filter/range-filter.component.ts
Fixes an issue where loading a corpus with a range filter would completely freeze the page.
> fix range filter crashing page

- backend/users/serializers.py
Changes the property used for `is_admin` in the user seraliser from `is_superuser` to `is_staff`
The function of `is_admin` in the user serializer determines whether the user sees a link to the admin menu in the frontend. Access to the admin menu is determined by staff status rather than superuser status, so this prevents an issue where a non-superuser staff member would not see the link to the admin menu.
> use is_staff for frontend serialisation

- backend/conftest.py
- backend/users/signals.py
Resolves the super-minor inconvenience of having to manually create an `allauth.account.models.EmailAddress` after `django createsuperuser`.
> Automatically verify superuser email adress

- backend/addcorpus/corpus.py
- frontend/src/app/document-view/document-view.component.html
- frontend/src/app/document-view/document-view.component.spec.ts
- frontend/src/app/document-view/document-view.component.ts
Improvements to the tabs used in the document view:
- Tabs have titles for clarity
- Each `text_content` field is shown as a separate tab, rather than having a single tab with the concatenated content. Though we did not have any existing corpora with more than one content field, so it's mostly for future corpora.
- The image tab is only shown if the corpus has configured an image mime type. close #1115
> document view tabs

- frontend/src/app/search/highlight-selector.component.ts
This seems to fix bug #1246. Reviewing this code, I realized that the setup with two ways of communicating changes of the queryModel to components, one through a `queryModel.update` Subject, and one through an `@Input` for `search-component`'s children, is rather hard to grasp. Worth revisiting (see #1247 ).
> close #1246 set highlight as switched off

- backend/corpora/peaceportal/tests/test_peace.py
close #1328 
My educated guess guess is that the errors from peace portal tests are caused by `os.walk` being non-deterministic on some operating systems. This fixes that.
> deterministic order for documents

- README.md
- documentation/First-time-setup.md
- documentation/Notes-for-development.md
- documentation/README.md
This is somewhat related to [updating our readme template](https://github.com/UUDigitalHumanitieslab/cookiecutter-webapp-deluxe/issues/47), as I wanted to use the suggested format for a real application.
This update moves all the developer-only instructions from the readme into the `/documentation` folder. And from its ashes doth rise a new README.
The new readme is based on this [template from UU FAIR ceatsheets](https://github.com/UtrechtUniversity/FAIR-Cheatsheets/blob/main/cheatsheets/FAIR_code_publishing/README_FAIR_code_publishing.md). It includes things like contact details, a link to the site, et cetera.
> move dev instructions to documentation, expand readme

- frontend/src/app/word-models/word-models.component.ts
Close #1359. The problem with repeated requests in case of a word that was missing in the word models was caused by a faulty condition in the `setStateFromParams` function.
> fix #1359: change condition for word models request

- frontend/src/app/word-models/similarity-chart/similarity-chart.component.html
- frontend/src/app/word-models/similarity-chart/similarity-chart.component.ts
Close #1315 : the colors next to the labels were missing. They are now reintroduced.
> Fix missing word model labels

- documentation/Making-a-release.md
- documentation/README.md
- documentation/Versioning.md
Adds documentation on versioning. Notably, I've tried to describe when a new version should be a patch/minor/major release, which I've found to be unclear on past occasions. Like many of our applications, I-analyzer cannot strictly conform to semver because it doesn't have an API, so I think it's useful to add some clarification.
It's also intended to provide some clarity for anyone who wants to host I-analyzer themselves.
This update is prescriptive rather than descriptive; read it as "going forward, we should do it like this". It mostly describes how we're already doing things, but not always.
> versioning docs

- frontend/src/app/document-view/document-view.component.html
- frontend/src/app/document-view/document-view.component.ts
I noticed the document view in the frontend was not displaying paragraph breaks:
This adds `<p>` tags based on `\n`.
> display paragraph breaks in document content

- frontend/src/app/document/document-preview/document-preview.component.html
- frontend/src/app/document/document-preview/document-preview.component.scss
- frontend/src/app/document/document-preview/document-preview.component.ts
- frontend/src/app/search/search-relevance.component.html
- frontend/src/app/shared/icons.ts
Changes the layout of document previews.
- content can use the full width of the preview
- preview includes a direct link to the document page
- no dead space for documents without an attached scan
close #1383
Screenshot:
Document with scan image:
This also changes the relevance score to just show the percentage (rather than a meter), which I think is clearer.
> document preview layout

- backend/addcorpus/es_settings.py
This branch is meant to close #1377. @lukavdplas , can you check whether this fixes the issue for you? I've seen the nltk check pop up multiple times during testing, that seems to not be happening anymore now. I think it's basically caused by a call to `load_corpus_definition`, so I'd expect the check to be run for every corpus that has stopword removal or stemming assigned, not infinitely, so there might still be a leakage issue elsewhere. In that case, this is just a cosmetic fix.
> conditional download of nltk stopwords

- frontend/src/app/models/visualization-selector.spec.ts
- frontend/src/app/models/visualization-selector.ts
- frontend/src/app/shared/dropdown/dropdown-item.directive.ts
- frontend/src/app/store/router-store.service.ts
- frontend/src/app/store/simple-store.ts
- frontend/src/app/store/store-sync.ts
- frontend/src/app/utils/params.ts
- frontend/src/app/visualization/visualization.component.html
- frontend/src/app/visualization/visualization.component.ts
- frontend/src/styles.scss
- part of #1403 : visualisation selection is now based on a `VisualizationSelector` class that uses the `StoreSync` functionality.
- close #1374 : reloading the visualisation page now works as it should, without lifecycle errors.
- if the user has not entered a search term, the term frequency and ngram visualisations are disabled rather than hidden (close #1371)
- dropdown items now support `[disabled]` input.
- error messages now have a header, which makes them a bit clearer.
- error messages don't replace the visualisation content, they just appear above it. This makes more sense to me, but I'm fine going back to the old behaviour.
> Refactor visualisation selection

- backend/corpora/parliament/canada.py
- backend/corpora/parliament/denmark-new.py
- backend/corpora/parliament/ireland.py
- backend/corpora/parliament/norway-new.py
In the first instance, this PR is intended to activate the Irish word models, but it also prepares addition of word models for Canada, Denmark and Norway.
> Add `word_model_path` to parliament corpora

- frontend/src/app/image-view/image-view.component.html
- frontend/src/app/shared/icons.ts
- fixes the previous/next icons on the scan pagination controls (those were swapped)
- hides the controls of the scan view when no image is available (close #1353)
> scan controls fixes

- backend/corpora/dbnl/dbnl.py
- backend/corpora/goodreads/goodreads.py
- backend/corpora/parliament/utils/field_defaults.py
- backend/corpora/peaceportal/utils/field_defaults.py
- backend/corpora/rechtspraak/rechtspraak.py
See #1117  : naming a field "URL" in the interface is unclear because I-analyzer also creates a unique URL for the document. This update clarifies the display names for most of those fields, by making it clear it's the URL _on Goodreads_ (or wherever).
The exception is this one:
https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/7b84d6b93d1876e5834e933249ca8c04ab7d89ba/backend/corpora/peaceportal/utils/field_defaults.py#L29-L36
where I don't know what it's supposed to link to. @BeritJanssen , could you add this?
> clarify fields named "URL"

- frontend/src/app/document-view/document-view.component.html
- frontend/src/app/document-view/document-view.component.ts
- frontend/src/app/models/corpus.ts
The coordinates field was rendered as `[object Object]`.
The coordinates [should be](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/geo-point.html) `Geopoint expressed as an array with the format: [ lon, lat]`.
I'm leaving this in draft in case we want to use a different representation in the elasticsearch index, because the order of lat/lon is inconsistent in some of the current indexed data.
> Fix rendering of geopoint array

- frontend/src/app/document-view/document-view.component.ts
The content of some fields can be an array of strings. Elasticsearch is pretty agnostic to this, which means on the frontend we need to do a type check.
> fix: only split document view content if it is a string

- frontend/src/app/document-view/document-view.component.html
- frontend/src/app/document-view/document-view.component.ts
- frontend/src/app/filter/filter-manager.component.spec.ts
- frontend/src/app/filter/filter-manager.component.ts
- frontend/src/app/services/auth.service.ts
- frontend/src/app/services/tag.service.spec.ts
- frontend/src/app/services/tag.service.ts
- frontend/src/app/tag/document-tags/document-tags.component.html
- frontend/src/app/tag/document-tags/document-tags.component.ts
- frontend/src/mock-data/auth.ts
Close #1483. After 4+ hours of trying to write a decent unit test for `document-view-component` which tests that tags are shown for authenticated users / not shown for unauthenticated users, I give up, and commit with a test only for the behaviour of the tag filter. 😞 Hope to figure out what the problem is soon. I think it's something to do with the `TagServiceMock` not mocking convincingly enough. But in the interest of a speedy release, perhaps better to just rely on my manual tests for now.
The only request to the backend is now one to the `user` endpoint:
> feat: introduce authService as dependency on tagService

- backend/addcorpus/python_corpora/load_corpus.py
- documentation/First-time-setup.md
- documentation/Indexing-corpora.md
As discussed with @BeritJanssen the READMEs did not include instructions to run the `loadcorpora` admin command before indexing, so I added it to the readmes.
I have also done a small fix. The documentation states that the keys in the `CORPORA` dictionary are case insensitive. However, the function `load_corpus_definition` does not match using lower case on both sides, so that using lower case is obligatory. I think this small change fixes this, but please check it carefully.
I'm asking a review from @lukavdplas because they have been most involved with documentation.
> Instructions to run loadcorpora admin command

- backend/corpora/peaceportal/tests/test_peace.py
The `test_peace_imports` regularly fails during CI ([example](https://github.com/UUDigitalHumanitieslab/I-analyzer/actions/runs/8832898059/job/24251085038)). Can we add an [xfail mark](https://docs.pytest.org/en/6.2.x/reference.html?highlight=xfail#pytest.mark.xfail) so it's less disruptive?
> mark peace import test xfail

- DockerfileElastic
- docker-compose.yaml
This PR is mainly a convenience for developing with Docker: switching between an instance of Elasticsearch *with* the [Annotated Text Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/8.6/mapper-annotated-text.html), needed for #956 , and one without, is rather annoying. This PR should not affect other development in Docker, but will make sure that working with a local volume that has an index with `annotated-text` mapping will be smooth.
> add annotated-text-plugin to Docker

- backend/corpora/guardianobserver/guardianobserver.py
Request from a participant at our last workshop: enables sorting by date in the guardian-observer corpus.
> enable sorting by date in guardianobserver

- backend/corpora/jewishmigration/jewishmigration.py
- backend/corpora/jewishmigration/test_jewishmigration.py
Originally `JMIG_DATA` was a URL, which I changed to also accept a local path. Now it's either `JMIG_DATA_URL` or `JMIG_DATA`, so we can't have a default URL or `JMIG_DATA` is never used.
> Do not provide a default JMIG_DATA_URL

- backend/addcorpus/models.py
- backend/addcorpus/permissions.py
- backend/addcorpus/serializers.py
- backend/addcorpus/tests/test_corpus_access.py
- backend/addcorpus/tests/test_corpus_views.py
- backend/addcorpus/tests/test_models.py
- backend/addcorpus/urls.py
- backend/addcorpus/views.py
- backend/download/views.py
- backend/es/views.py
- backend/ianalyzer/urls.py
- backend/media/views.py
- backend/tag/views.py
- backend/users/conftest.py
- backend/users/models.py
- backend/users/tests/test_corpus_access.py
- backend/visualization/views.py
- backend/wordmodels/tests/test_wordmodels_views.py
- backend/wordmodels/views.py
- frontend/src/app/corpus-info/corpus-info.component.ts
- frontend/src/app/models/corpus.ts
- frontend/src/app/services/api.service.ts
- frontend/src/app/services/corpus.service.ts
- frontend/src/mock-data/api.ts
- frontend/src/mock-data/corpus.ts
This update changes the backend API to allow uploading corpus documentation (part of https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/1573). It also makes some quality improvements to permissions in corpus-related views.
The corpus documentation view now has create/update/delete endpoints (accessible to admin users). Some changes to the view to make that more convenient:
- The corpus name is now an optional query parameter, e.g. `/api/corpus/documentation/dbnl/` -> `/api/corpus/documentation/?corpus=dbnl`. It's also included in the JSON data, so you can create/update on `/api/corpus/documentation/`.
- The view includes both the original template for the documentation, and the rendered version (the latter is read-only).
- The order of pages is now included as a (read-only) …
> Edit corpus documention in API

- frontend/src/app/document-view/document-view.component.spec.ts
- frontend/src/app/shared/tabs/tabs.component.html
- frontend/src/app/shared/tabs/tabs.component.spec.ts
- frontend/src/app/shared/tabs/tabs.component.ts
Fixes two issues with tabs:
- The template wasn't using the `tab` role correctly - it should be assigned to the direct children of the `tablist` element.
- https://github.com/UUDigitalHumanitieslab/I-analyzer/pull/1616 had fixed invalid DOM ids being used for tabs, but not for the corresponding tabpanels.
> fix tabs IDs en ARIA roles

- backend/corpora/jewishmigration/jewishmigration.py
This PR adds a couple of lines to send a get request with an authorization header in case an api key is defined in the settings. It also fixes a problem with `JewishMigration`'s `es_alias` being set to "peaceportal" (inherited from `PeacePortal` parent class).
> Jewishmigration: request data with API key

- backend/es/es_index.py
When indexing the JewishMigration corpus, the process stopped after ca. 300 documents, with the following message: `elasticsearch.helpers.BulkIndexError: 1 document(s) failed to index.` To me it seemed an overkill to let the whole process fail on this, so I wrapped the `streaming_bulk` operation in a try / except clause. Unfortunately, the error message is not more specific about which document failed and why. Curiously, locally the indexing operation finishes with 1960 documents having been indexed, i.e., all documents currently in this corpus.
> Add try/except clause around streaming_bulk operation

- backend/corpora/jewishmigration/test_jewishmigration.py
- backend/es/es_alias.py
- backend/es/es_index.py
- backend/es/tests/test_es_index.py
For now, this PR should fix #1656 . Perhaps not the prettiest solution, but I wanted to avoid repeated requests to the Elasticsearch client just to reaffirm the current version number. Perhaps in the long run, some database bookkeeping of index versions would not be a bad idea, but let's discuss this at a later point.
> fix: let es_index.create return versioned index name

- backend/corpora/guardianobserver/guardianobserver.py
- backend/corpora/times/times.py
This PR makes it possible to easily test / deploy word models for Times and Guardian by modifying a server's `settings.py`
> Add word_model_path to times and guardian corpus

- backend/corpora/jewishmigration/jewishmigration.py
- backend/corpora/peaceportal/utils/field_defaults.py
I wanted to add visualizations for Jewishmigration and noticed in the process that the Peace Portal `field_defaults` used the old format for specifying visualizations. This branch should fix that.
> Fix Peace Portal visualizations & add visualization for Jewishmigration

- backend/ianalyzer/common_settings.py
- backend/ianalyzer/settings.py
- frontend/src/app/login/registration/registration.component.html
- frontend/src/app/login/reset-password/request-reset.component.html
Following a SO post, I decided to keep the username in the emails, but replace dots in the username by a square dot. Bad luck for a "dotty" user who wants to copy / paste their username, but I think it is still more user friendly that way. Also thought to include a fix for the registration form to allow longer domains.
> Fix registration issues

- backend/addcorpus/models.py
Before, the existence of named entities was retrieved from the mappings. I decided to replace this by a search with a query to check if any fields starting with "ner:*" are actually in the documents. Less wordy this way, and with `size=0`, this request takes only 2-7 milliseconds to perform on the largest corpus we have at the moment (dutchnewspapers-all).
> Fix NER check

- backend/ianalyzer/common_settings.py
- backend/users/throttles.py
- backend/users/urls.py
- backend/users/views.py
- frontend/src/app/login/registration/registration.component.html
- frontend/src/app/login/registration/registration.component.ts
@tymees does this throttle implementation look reasonable?
Team, do we want `DEFAULT_THROTTLE_RATES` in common or local settings? And what's a rate that's high enough for potential peak registration periods (like a course/lecture)?
> Add basic registration ratelimit

- .github/workflows/backend-build-and-push.yml
- .github/workflows/backend-build-and-test.yml
- .github/workflows/backend-test.yml
- .github/workflows/frontend-build-and-push.yml
- .github/workflows/frontend-build-and-test.yml
- .github/workflows/frontend-test.yml
- .github/workflows/scheduled-build-and-push.yml
- docker-compose.yaml
This branch reworks the current strategy of GitHub actions, which often fail due to failed pushes to the registry. It tries to limit the pushes to the registry with the following strategy:
- every push to `feature/**`, `bugfix/**`, `hotfix/**`, `release/**`, `develop` and `master` will trigger a test action, using the `:latest` image of frontend / backend / elasticsearch, respectively.
- in dependabot/feature/bugfix/hotfix branches: when `requirements.txt` or `yarn.lock` have been touched, another action will be triggered: we will run tests *without* using the image, this to avoid failing tests due to missing / outdated libraries. Unfortunately I cannot see how I would then avoid still triggering the above action, as it does not seem we can tell GHA to run actions "if this path is …
> Overhaul GitHub actions once more

- backend/addcorpus/es_mappings.py
- backend/corpora/parliament/finland.py
- backend/corpora/parliament/ireland.py
- backend/corpora/parliament/utils/field_defaults.py
This PR removes the argument `updated_highlighting` from the `main_content_mapping`, as we have updated all indices now with the term vector, and this should be standard behaviour.
The branch also fixes some issues with parliamentary corpora: `finland` didn't yet set a language, and `ireland` overrode the es_mappings in a way that's not necessary anymore when not passing a `language` argument to `speech()`.
> Always add term vector to main content field and fix mappings in some parliamentary corpora

- frontend/src/app/home/home.component.html
Adds a message to point users to our user survey. The plan is to keep this message up for a month or so and then remove it.
This solution is very low-tech - the message can't be dismissed but it's also not too distracting or obtrusive.
This only appears on the home page, not on the search interface. I'm hoping that that way, users will see it but it won't get annoying.
> add survey link

- frontend/src/app/visualization/barchart/histogram.component.ts
close #1683
Fixes the number of documents / term frequency visualisations for numeric fields without an upper/lower bound configured. Also addresses an issue with float fields where the number of values may be more than `upper - lower`.
Fix: ensure that the bin limit is at least 100.
The result still isn't great, to be honest. In a corpus like DBNL, you get the top 100 years, which is a bit weird in a 700-year range. The proper fix would be to use a [histogram aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html) rather than a [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html). But that would be a lot more work.
> set minimum size for terms aggregation in visualisation

- backend/es/es_alias.py
- backend/es/tests/test_alias.py
The first attempt to index with the new alias / versioning strategy triggered an error, as there were not any indices yet under the alias. This branch fixes that.
> Fix problem with es index version when no indices exist

- backend/corpora/jewishmigration/jewishmigration.py
- backend/corpora/jewishmigration/test_jewishmigration.py
This branch makes sure that the "Estimated Centuries" field can be filtered on, useful to compare the map over time.
Note: for this to work properly, will need to reindex the JewishMigration corpus once more, to convert from integer to keyword field.
> Add Estimated Centuries filter in Jewish Migration

- frontend/src/app/home/home.component.html
The link to the user survey has been up for a while now (#1682), so I think we can remove it with the next release.
> remove user survey link

- backend/corpora/gallica/conftest.py
- backend/corpora/gallica/figaro.py
- backend/corpora/gallica/gallica.py
- backend/corpora/gallica/tests/test_import.py
There is a throttle on the Gallica API, which caused periodical crashes & necessity for manual restarts. This branch automates those restarts, and it now seems to run smoothly (albeit very slowly) over the remaining Figaro data.
> Gallica: automate restart after failed HTTP requests

- backend/addcorpus/python_corpora/tests/test_times_source.py
- backend/es/conftest.py
- backend/es/tests/test_alias.py
- backend/es/tests/test_es_index.py
- backend/ianalyzer/settings_test.py
Tiny change to the names used for indices created in unit tests.
The affected indices are now caught by the `test_index_cleanup` fixture, which removes test indices at the start and end of each session. This fixes a problem where tests may fail because the previous session was not completed (and lingering indices are messing up the test).
> utilise session cleanup for test indices

- backend/addcorpus/tests/test_corpus_views.py
- backend/addcorpus/urls.py
- backend/addcorpus/views.py
- frontend/package.json
- frontend/src/app/corpus-definitions/definition-json-upload/definition-json-upload.component.html
- frontend/src/app/corpus-definitions/definition-json-upload/definition-json-upload.component.spec.ts
- frontend/src/app/corpus-definitions/definition-json-upload/definition-json-upload.component.ts
- frontend/src/app/corpus-definitions/form/corpus-form/corpus-form.component.spec.ts
- frontend/src/app/corpus-definitions/form/field-form/field-form.component.spec.ts
- frontend/src/app/corpus-definitions/form/meta-form/meta-form.component.spec.ts
- frontend/src/app/services/api.service.ts
- frontend/src/mock-data/api.ts
- frontend/yarn.lock
- Adds an API endpoint for the corpus JSON schema (close #1737)
- Validates corpus JSON uploads against the schema. The feedback for invalid JSONs is taken straight from the validation package.
Screenshot:
> json schema endpoint + validation

- backend/corpora/dutchnewspapers/description/description_public.md
- backend/corpora/dutchnewspapers/dutchnewspapers_public.py
Part of https://github.com/CentreForDigitalHumanities/I-analyzer/issues/991
Adds an info page for the public Delpher corpus. Also includes a (Jill-approved) explanation about accessing the full dataset.
> delpher documentation

- backend/ianalyzer/celery.py
- backend/indexing/admin.py
- backend/indexing/run_job.py
- documentation/Indexing-corpora.md
Part of https://github.com/CentreForDigitalHumanities/I-analyzer/issues/1697
Adds an action to start index jobs from the admin site. With this addition, you could create, index, and publish a corpus entirely through the admin, no terminal required.
I'm not sure if kicking off indexing from the admin site is the future, but the action is just a few lines of code. The main addition is that index jobs can now be scheduled through celery, which is something we need for https://github.com/CentreForDigitalHumanities/I-analyzer/issues/1007
Not implemented:
- interrupting jobs
- if we want the admin site as a viable tool for indexing, you need some way to see error logs.
> async index jobs

- .github/workflows/fallback-test.yml
- backend/addcorpus/tests/test_citation.py
This is a potential fix for the issue that the "Test Backend" and "Test Frontend" checks are required for merging, but skipped if there are no changes in their respective directories. So if you make a PR with, say, no changes to the frontend, you have to bypass branch protection rules to merge.
Solution from: https://github.com/orgs/community/discussions/26251#discussioncomment-3250964
This adds a "fallback" test workflow that is always run and always succeeds. Because the fallback jobs are also called "Test Backend" and "Test Frontend", they will satisfy the branch protection rules. But if the real test workflow is also triggered, github will require both to succeed.
> add fallback test workflow
